\set ON_ERROR_STOP on
CREATE ROLE capacity_migration LOGIN PASSWORD :'MIGRATION_PASSWORD';
CREATE ROLE capacity_app LOGIN PASSWORD :'APP_PASSWORD';
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE CREATE, TEMP ON DATABASE postgres FROM PUBLIC;
GRANT CONNECT ON DATABASE postgres TO capacity_migration, capacity_app;
CREATE SCHEMA capacity_board AUTHORIZATION capacity_migration;
