version: '3.8'
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:${CHVER:-latest}'
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
    depends_on:
      - clickhouse-keeper
    networks:
      - network1

  clickhouse-keeper:
    image: 'clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}'
    user: '101:101'
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - '127.0.0.1:9181:9181'
    networks:
      - network1

  dagster_webserver:
  # todo: for production, set up dagster-webserver and the dagster-daemon
    build:
      context: .
      dockerfile: ./dagster/Dockerfile
    container_name: dagster_webserver
    ports:
      - 3000:3000
    volumes: 
      - ${PWD}/user_code:/opt/dagster/dagster_home/user_code
    networks:
      - network1


networks:
  network1:
    driver: bridge
    name: network1
