import { expect, type Page } from "@playwright/test";
import { chooseOption, verifyFolderDisclosure, verifyFolderTemplateIsolation } from "./controls";

/** Signed-in links workspace, no dialog open. Leaves filters clear and links intact. */
export async function verifyFolders(page: Page) {
  const folderName = "Browser launch folder";
  const renamed = "Browser release folder";
  const title = "Folder verification";
  await page.getByRole("button", { name: "Create a link", exact: true }).click();
  await page.getByLabel("Destination URL").fill("https://example.com/folder-verification");
  await page.getByLabel("Link title").fill(title);
  await page.locator(".folder-trigger").click();
  const search = page.getByRole("textbox", { name: "Search or create a folder" });
  await expect(search).toBeFocused();
  await verifyFolderDisclosure(page);
  await page.screenshot({ path: "test-results/create-folder-selector.png" });
  await search.fill(folderName);
  await search.press("Shift+Enter");
  await expect(page.locator("dialog[open]")).toBeVisible();
  await expect(page.getByLabel("Link title")).toHaveValue(title);
  await search.press("Escape");
  await expect(search).not.toBeVisible();
  await expect(page.locator(".folder-trigger")).toBeFocused();
  await expect(page.locator("dialog[open]")).toBeVisible();
  await page.locator(".folder-trigger").click();
  await page.getByRole("button", { name: `Create “${folderName}”`, exact: true }).click();
  await expect(page.locator(".folder-trigger")).toContainText(folderName);
  await page.getByRole("button", { name: "Create link", exact: true }).click();
  await expect(page.locator("dialog[open]")).not.toBeVisible();
  await expect(page.getByRole("button", { name: title, exact: true })).toBeVisible();
  await page.reload();
  await chooseOption(page, page.getByRole("combobox", { name: "Filter links by folder" }), folderName);
  await expect(page.locator(".link-row")).toHaveCount(1);
  await page.getByRole("button", { name: `Edit ${title}`, exact: true }).click();
  await expect(page.locator(".folder-trigger")).toContainText(folderName);
  await verifyFolderTemplateIsolation(page, folderName, "desktop");
  // Exercise the picker in a compact editor and use its keyboard selection.
  await page.setViewportSize({ width: 390, height: 600 });
  await verifyFolderTemplateIsolation(page, folderName, "mobile");
  await page.locator(".folder-trigger").click();
  await search.fill("browser launch");
  await expect(page.locator(".folder-popup").getByRole("button", { name: folderName, exact: true })).toBeVisible();
  const popup = (await page.locator(".folder-popup").boundingBox())!;
  expect(popup.x).toBeGreaterThanOrEqual(0);
  expect(popup.x + popup.width).toBeLessThanOrEqual(391);
  expect(popup.y).toBeGreaterThanOrEqual(0);
  expect(popup.y + popup.height).toBeLessThanOrEqual(601);
  await search.press("ArrowDown");
  await expect(page.locator(".folder-popup").getByRole("button", { name: "No folder", exact: true })).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(page.locator(".folder-trigger")).toContainText("No folder");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.locator("dialog[open]")).not.toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await chooseOption(page, page.getByRole("combobox", { name: "Filter links by folder" }), "No folder");
  await page.getByRole("button", { name: `Edit ${title}`, exact: true }).click();
  await page.locator(".folder-trigger").click();
  await page.locator(".folder-popup").getByRole("button", { name: folderName, exact: true }).click();
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.locator("dialog[open]")).not.toBeVisible();
  await page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Folders", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Folders", exact: true })).toBeVisible();
  await page.reload();
  const extraFolders = ["Page-created folder", "Campaign reports and saved links from the summer launch"];
  for (const name of extraFolders) {
    await page.getByLabel("New folder", { exact: true }).fill(name);
    await page.getByRole("button", { name: "Create folder", exact: true }).click();
    await expect(page.getByRole("article", { name, exact: true })).toBeVisible();
  }
  await expect(page.locator(".folder-grid .folder-tile")).toHaveCount(3);
  const folderLink = page.getByRole("link", { name: folderName, exact: true });
  await expect(folderLink).toHaveAttribute("href", /^\/links\?folderId=/);
  await folderLink.click();
  await expect(page).toHaveURL(/\/links\?folderId=/);
  const filteredUrl = page.url();
  expect(new URL(filteredUrl).searchParams.get("folderId")).toMatch(/^[0-9a-f-]{36}$/i);
  const folderFilter = page.getByRole("combobox", { name: "Filter links by folder", exact: true });
  await expect(folderFilter).toContainText(folderName);
  await expect(page.locator(".link-row")).toHaveCount(1);
  await expect(page.getByRole("button", { name: title, exact: true })).toBeVisible();
  await page.reload();
  await expect(folderFilter).toContainText(folderName);
  await expect(page.locator(".link-row")).toHaveCount(1);
  await chooseOption(page, folderFilter, "All folders");
  await expect.poll(() => new URL(page.url()).searchParams.has("folderId")).toBe(false);
  await page.goBack();
  await expect(folderFilter).toContainText(folderName);
  await expect(page.locator(".link-row")).toHaveCount(1);
  await page.goBack();
  await expect(page.getByRole("heading", { name: "Folders", exact: true })).toBeVisible();
  await page.goForward();
  await expect(folderFilter).toContainText(folderName);
  await expect(page.locator(".link-row")).toHaveCount(1);
  await page.getByRole("textbox", { name: "Search links", exact: true }).fill("No matching folder link");
  await page.getByRole("button", { name: "Clear filters", exact: true }).click();
  await expect(folderFilter).toContainText("All folders");
  await expect(page.getByRole("textbox", { name: "Search links", exact: true })).toHaveValue("");
  await expect.poll(() => new URL(page.url()).searchParams.has("folderId")).toBe(false);
  await page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Folders", exact: true }).click();
  const folderActions = page.getByRole("button", { name: `Actions for ${folderName}`, exact: true });
  await folderActions.focus();
  await folderActions.press("ArrowDown");
  await expect(page.getByRole("menuitem", { name: "Rename", exact: true })).toBeFocused();
  await expect(page).toHaveURL(/\/folders$/);
  await page.keyboard.press("ArrowDown");
  await expect(page.getByRole("menuitem", { name: "Delete", exact: true })).toBeFocused();
  await page.keyboard.press("Home");
  await expect(page.getByRole("menuitem", { name: "Rename", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("menu")).not.toBeVisible();
  await expect(folderActions).toBeFocused();
  await folderActions.click();
  await page.getByRole("heading", { name: "Folders", exact: true }).click();
  await expect(page.getByRole("menu")).not.toBeVisible();
  await page.screenshot({ path: "test-results/folders-desktop.png", fullPage: false });
  await page.setViewportSize({ width: 390, height: 600 });
  await page.getByRole("button", { name: "Open navigation", exact: true }).click();
  const help = page.getByRole("button", { name: "Keyboard shortcuts", exact: true });
  await expect(help).toBeVisible();
  expect(await help.evaluate((button) => button.parentElement?.nextElementSibling?.classList.contains("sidebar-credits"))).toBe(true);
  await page.screenshot({ path: "test-results/sidebar-mobile.png", fullPage: false });
  await help.click();
  await expect(page.getByRole("heading", { name: "Keyboard shortcuts", exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(help).toBeFocused();
  await page.getByRole("button", { name: "Close navigation", exact: true }).click();
  await page.screenshot({ path: "test-results/folders-mobile.png", fullPage: false });
  await folderActions.click();
  const menuBox = (await page.getByRole("menu").boundingBox())!;
  expect(menuBox.x).toBeGreaterThanOrEqual(0);
  expect(menuBox.x + menuBox.width).toBeLessThanOrEqual(390);
  expect(menuBox.y).toBeGreaterThanOrEqual(0);
  expect(menuBox.y + menuBox.height).toBeLessThanOrEqual(600);
  await page.screenshot({ path: "test-results/folder-actions-mobile.png", fullPage: false });
  await page.getByRole("menuitem", { name: "Rename", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByLabel("Folder name", { exact: true })).toBeFocused();
  await page.getByLabel("Folder name", { exact: true }).fill("Canceled rename");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await expect(folderActions).toBeFocused();
  await expect(page.getByRole("article", { name: folderName, exact: true })).toBeVisible();
  await page.setViewportSize({ width: 320, height: 600 });
  await folderActions.click();
  const narrowMenu = (await page.getByRole("menu").boundingBox())!;
  expect(narrowMenu.x).toBeGreaterThanOrEqual(0);
  expect(narrowMenu.x + narrowMenu.width).toBeLessThanOrEqual(320);
  expect(narrowMenu.y).toBeGreaterThanOrEqual(0);
  expect(narrowMenu.y + narrowMenu.height).toBeLessThanOrEqual(600);
  await page.keyboard.press("Escape");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await folderActions.click();
  await page.getByRole("menuitem", { name: "Rename", exact: true }).click();
  await page.getByLabel("Folder name", { exact: true }).fill(renamed);
  await page.getByRole("button", { name: "Save name", exact: true }).click();
  await expect(page.getByRole("article", { name: renamed, exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: `Actions for ${renamed}`, exact: true })).toBeFocused();
  await page.getByRole("link", { name: renamed, exact: true }).click();
  await expect(folderFilter).toContainText(renamed);
  await expect(page.getByRole("button", { name: title, exact: true })).toBeVisible();
  await page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Folders", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Folders", exact: true })).toBeVisible();
  for (const name of extraFolders) {
    await page.getByRole("button", { name: `Actions for ${name}`, exact: true }).click();
    await page.getByRole("menuitem", { name: "Delete", exact: true }).click();
    await page.getByRole("button", { name: "Delete folder", exact: true }).click();
    await expect(page.getByRole("article", { name, exact: true })).not.toBeVisible();
  }
  await page.getByRole("button", { name: `Actions for ${renamed}`, exact: true }).click();
  await page.getByRole("menuitem", { name: "Delete", exact: true }).click();
  await expect(page.getByText("Links will move to No folder.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Delete folder", exact: true }).click();
  await expect(page.getByRole("article", { name: renamed, exact: true })).not.toBeVisible();
  await expect(page.getByLabel("New folder", { exact: true })).toBeFocused();
  await page.goto(filteredUrl);
  await expect(page.getByRole("heading", { name: "Folder unavailable", exact: true })).toBeVisible();
  await expect(folderFilter).toContainText("Unavailable folder");
  await expect(page.locator(".link-row")).toHaveCount(0);
  await page.getByRole("button", { name: "Clear filters", exact: true }).click();
  await expect.poll(() => new URL(page.url()).searchParams.has("folderId")).toBe(false);
  await page.reload();
  await chooseOption(page, page.getByRole("combobox", { name: "Filter links by folder" }), "No folder");
  await expect(page.getByRole("button", { name: title, exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Filter links by folder" }).click();
  await expect(page.getByRole("option", { name: renamed, exact: true })).toHaveCount(0);
  await page.getByRole("option", { name: "All folders", exact: true }).click();
}
