// Code generated by ent, DO NOT EDIT.

package item

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"example.com/playlist-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldID, id))
}

// PlaylistID applies equality check predicate on the "playlist_id" field. It's identical to PlaylistIDEQ.
func PlaylistID(v uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldPlaylistID, v))
}

// TrackID applies equality check predicate on the "track_id" field. It's identical to TrackIDEQ.
func TrackID(v uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldTrackID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldPosition, v))
}

// PlaylistIDEQ applies the EQ predicate on the "playlist_id" field.
func PlaylistIDEQ(v uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldPlaylistID, v))
}

// PlaylistIDNEQ applies the NEQ predicate on the "playlist_id" field.
func PlaylistIDNEQ(v uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldPlaylistID, v))
}

// PlaylistIDIn applies the In predicate on the "playlist_id" field.
func PlaylistIDIn(vs ...uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldPlaylistID, vs...))
}

// PlaylistIDNotIn applies the NotIn predicate on the "playlist_id" field.
func PlaylistIDNotIn(vs ...uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldPlaylistID, vs...))
}

// TrackIDEQ applies the EQ predicate on the "track_id" field.
func TrackIDEQ(v uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldTrackID, v))
}

// TrackIDNEQ applies the NEQ predicate on the "track_id" field.
func TrackIDNEQ(v uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldTrackID, v))
}

// TrackIDIn applies the In predicate on the "track_id" field.
func TrackIDIn(vs ...uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldTrackID, vs...))
}

// TrackIDNotIn applies the NotIn predicate on the "track_id" field.
func TrackIDNotIn(vs ...uuid.UUID) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldTrackID, vs...))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldPosition, v))
}

// HasPlaylist applies the HasEdge predicate on the "playlist" edge.
func HasPlaylist() predicate.Item {
	return predicate.Item(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlaylistTable, PlaylistColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaylistWith applies the HasEdge predicate on the "playlist" edge with a given conditions (other predicates).
func HasPlaylistWith(preds ...predicate.Playlist) predicate.Item {
	return predicate.Item(func(s *sql.Selector) {
		step := newPlaylistStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTrack applies the HasEdge predicate on the "track" edge.
func HasTrack() predicate.Item {
	return predicate.Item(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TrackTable, TrackColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTrackWith applies the HasEdge predicate on the "track" edge with a given conditions (other predicates).
func HasTrackWith(preds ...predicate.Track) predicate.Item {
	return predicate.Item(func(s *sql.Selector) {
		step := newTrackStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Item) predicate.Item {
	return predicate.Item(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Item) predicate.Item {
	return predicate.Item(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Item) predicate.Item {
	return predicate.Item(sql.NotPredicates(p))
}
