# Generated by Django 5.2.17 on 2026-10-02 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('asset_tag', ''), _negated=True), name='item_tag_not_empty'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='item_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_loans', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='board.item')),
            ],
            options={
                'ordering': ['-checked_out_at', '-id'],
                'indexes': [models.Index(fields=['borrower', 'returned_at'], name='borrower_active_loans')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('item',), name='one_active_loan_per_item'), models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('checked_out_at')), _connector='OR'), name='return_after_checkout')],
            },
        ),
    ]
