// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "position", Type: field.TypeInt},
		{Name: "playlist_id", Type: field.TypeUUID},
		{Name: "track_id", Type: field.TypeUUID},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "items_playlists_items",
				Columns:    []*schema.Column{ItemsColumns[2]},
				RefColumns: []*schema.Column{PlaylistsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "items_tracks_items",
				Columns:    []*schema.Column{ItemsColumns[3]},
				RefColumns: []*schema.Column{TracksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "item_playlist_id_track_id",
				Unique:  true,
				Columns: []*schema.Column{ItemsColumns[2], ItemsColumns[3]},
			},
			{
				Name:    "items_playlist_position",
				Unique:  true,
				Columns: []*schema.Column{ItemsColumns[2], ItemsColumns[1]},
			},
		},
	}
	// PlaylistsColumns holds the columns for the "playlists" table.
	PlaylistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 80},
		{Name: "revision", Type: field.TypeInt, Default: 1},
		{Name: "owner_id", Type: field.TypeUUID},
	}
	// PlaylistsTable holds the schema information for the "playlists" table.
	PlaylistsTable = &schema.Table{
		Name:       "playlists",
		Columns:    PlaylistsColumns,
		PrimaryKey: []*schema.Column{PlaylistsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "playlists_accounts_playlists",
				Columns:    []*schema.Column{PlaylistsColumns[3]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "playlist_owner_id_id",
				Unique:  false,
				Columns: []*schema.Column{PlaylistsColumns[3], PlaylistsColumns[0]},
			},
		},
	}
	// TracksColumns holds the columns for the "tracks" table.
	TracksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 80},
		{Name: "artist", Type: field.TypeString, Size: 80},
		{Name: "duration_seconds", Type: field.TypeInt},
	}
	// TracksTable holds the schema information for the "tracks" table.
	TracksTable = &schema.Table{
		Name:       "tracks",
		Columns:    TracksColumns,
		PrimaryKey: []*schema.Column{TracksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		ItemsTable,
		PlaylistsTable,
		TracksTable,
	}
)

func init() {
	ItemsTable.ForeignKeys[0].RefTable = PlaylistsTable
	ItemsTable.ForeignKeys[1].RefTable = TracksTable
	PlaylistsTable.ForeignKeys[0].RefTable = AccountsTable
}
