// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WebhookActivity struct {
	EventID       pgtype.UUID        `json:"event_id"`
	IntegrationID pgtype.UUID        `json:"integration_id"`
	Path          string             `json:"path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WebhookCounter struct {
	IntegrationID pgtype.UUID `json:"integration_id"`
	EventCount    int64       `json:"event_count"`
}

type WebhookEvent struct {
	ID              pgtype.UUID        `json:"id"`
	IntegrationID   pgtype.UUID        `json:"integration_id"`
	ExternalEventID string             `json:"external_event_id"`
	Payload         []byte             `json:"payload"`
	PayloadSha256   string             `json:"payload_sha256"`
	Status          string             `json:"status"`
	Attempts        int32              `json:"attempts"`
	LastError       pgtype.Text        `json:"last_error"`
	AvailableAt     pgtype.Timestamptz `json:"available_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

type WebhookIntegration struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}
