// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEvent = `-- name: ClaimEvent :one
SELECT id, integration_id, external_event_id, payload, payload_sha256, status, attempts, last_error, available_at, created_at, processed_at FROM webhook.events
WHERE status = 'pending' AND available_at <= clock_timestamp()
ORDER BY available_at, created_at, id
LIMIT 1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimEvent(ctx context.Context) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, claimEvent)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ExternalEventID,
		&i.Payload,
		&i.PayloadSha256,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const completeEvent = `-- name: CompleteEvent :exec
UPDATE webhook.events SET status = 'processed', attempts = attempts + 1,
    processed_at = clock_timestamp(), last_error = NULL WHERE id = $1
`

func (q *Queries) CompleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeEvent, id)
	return err
}

const failEvent = `-- name: FailEvent :exec
UPDATE webhook.events SET attempts = attempts + 1,
    status = CASE WHEN attempts + 1 >= 3 THEN 'failed' ELSE 'pending' END,
    last_error = $2, available_at = clock_timestamp() + ((attempts + 1) * interval '1 second')
WHERE id = $1
`

type FailEventParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailEvent(ctx context.Context, arg FailEventParams) error {
	_, err := q.db.Exec(ctx, failEvent, arg.ID, arg.LastError)
	return err
}

const getCounter = `-- name: GetCounter :one
SELECT event_count FROM webhook.counters WHERE integration_id = $1
`

func (q *Queries) GetCounter(ctx context.Context, integrationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getCounter, integrationID)
	var event_count int64
	err := row.Scan(&event_count)
	return event_count, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, integration_id, external_event_id, payload, payload_sha256, status, attempts, last_error, available_at, created_at, processed_at FROM webhook.events WHERE integration_id = $1 AND external_event_id = $2
`

type GetEventParams struct {
	IntegrationID   pgtype.UUID `json:"integration_id"`
	ExternalEventID string      `json:"external_event_id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.IntegrationID, arg.ExternalEventID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ExternalEventID,
		&i.Payload,
		&i.PayloadSha256,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const incrementCounter = `-- name: IncrementCounter :execrows
UPDATE webhook.counters SET event_count = event_count + 1 WHERE integration_id = $1
`

func (q *Queries) IncrementCounter(ctx context.Context, integrationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementCounter, integrationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO webhook.events (integration_id, external_event_id, payload, payload_sha256)
VALUES ($1, $2, $3, $4) ON CONFLICT (integration_id, external_event_id) DO NOTHING
RETURNING id, integration_id, external_event_id, payload, payload_sha256, status, attempts, last_error, available_at, created_at, processed_at
`

type InsertEventParams struct {
	IntegrationID   pgtype.UUID `json:"integration_id"`
	ExternalEventID string      `json:"external_event_id"`
	Payload         []byte      `json:"payload"`
	PayloadSha256   string      `json:"payload_sha256"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.IntegrationID,
		arg.ExternalEventID,
		arg.Payload,
		arg.PayloadSha256,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ExternalEventID,
		&i.Payload,
		&i.PayloadSha256,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const integrationExists = `-- name: IntegrationExists :one
SELECT EXISTS (SELECT 1 FROM webhook.integrations WHERE id = $1)
`

func (q *Queries) IntegrationExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, integrationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordActivity = `-- name: RecordActivity :exec
INSERT INTO webhook.activity (event_id, integration_id, path) VALUES ($1, $2, $3)
`

type RecordActivityParams struct {
	EventID       pgtype.UUID `json:"event_id"`
	IntegrationID pgtype.UUID `json:"integration_id"`
	Path          string      `json:"path"`
}

func (q *Queries) RecordActivity(ctx context.Context, arg RecordActivityParams) error {
	_, err := q.db.Exec(ctx, recordActivity, arg.EventID, arg.IntegrationID, arg.Path)
	return err
}
