// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePlaylistInput struct {
	Name     string   `json:"name"`
	TrackIds []string `json:"trackIds"`
}

type Mutation struct {
}

type Playlist struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Revision int             `json:"revision"`
	Items    []*PlaylistItem `json:"items"`
}

type PlaylistItem struct {
	Position int    `json:"position"`
	Track    *Track `json:"track"`
}

type PlaylistPage struct {
	Playlists  []*Playlist `json:"playlists"`
	NextCursor *string     `json:"nextCursor,omitempty"`
}

type Query struct {
}

type ReorderInput struct {
	ID               string   `json:"id"`
	ExpectedRevision int      `json:"expectedRevision"`
	TrackIds         []string `json:"trackIds"`
}

type Track struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Artist          string `json:"artist"`
	DurationSeconds int    `json:"durationSeconds"`
}
