package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"example.com/playlist-api/graph/model"
	"example.com/playlist-api/internal/app"
)

// CreatePlaylist is the resolver for the createPlaylist field.
func (r *mutationResolver) CreatePlaylist(ctx context.Context, input model.CreatePlaylistInput) (*model.Playlist, error) {
	return app.Create(ctx, input)
}

// ReorderPlaylist is the resolver for the reorderPlaylist field.
func (r *mutationResolver) ReorderPlaylist(ctx context.Context, input model.ReorderInput) (*model.Playlist, error) {
	return app.Reorder(ctx, input)
}

// Tracks is the resolver for the tracks field.
func (r *queryResolver) Tracks(ctx context.Context, limit int) ([]*model.Track, error) {
	return app.Tracks(ctx, limit)
}

// Playlists is the resolver for the playlists field.
func (r *queryResolver) Playlists(ctx context.Context, limit int, cursor *string) (*model.PlaylistPage, error) {
	return app.List(ctx, limit, cursor)
}

// Playlist is the resolver for the playlist field.
func (r *queryResolver) Playlist(ctx context.Context, id string) (*model.Playlist, error) {
	return app.Read(ctx, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
