// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Playlist is the predicate function for playlist builders.
type Playlist func(*sql.Selector)

// Track is the predicate function for track builders.
type Track func(*sql.Selector)
