import schemafile_pb2  # Module generated by 'protoc'
from google.protobuf import text_format

def create_user_data_message(name, surname, age, emails): # Modified arguments
    """
    Creates and populates a UserData Protobuf message.
    """
    user = schemafile_pb2.UserData()
    user.name = name
    user.surname = surname
    user.age = age
    user.email_addresses.extend(emails)
    return user

# The data for our example users
data_to_serialize = [
    {"name": "Aisha", "surname": "Khan", "age": 28, "emails": ["aisha.khan@example.com", "aisha.k@mymail.net"]},
    {"name": "Javier", "surname": "Rodriguez", "age": 35, "emails": ["javier.rodriguez@company.org", "j.rodriguez@email.co"]},
    {"name": "Mei", "surname": "Ling", "age": 22, "emails": ["mei.ling@webmail.com", "m.ling@personal.dev"]},
]

output_filename = "protobuf_messages.bin"

# Open the binary file in write-binary mode ('wb')
with open(output_filename, "wb") as f:
    for item in data_to_serialize:
        # Create a Protobuf message instance for the current user
        message = create_user_data_message(
            item["name"],
            item["surname"],
            item["age"],
            item["emails"]
        )

        # Serialize the message and add the length prefix
        f.write(message.SerializeDelimitedToString())
