[clickhouse]
username = "default"
password = ""
host = "localhost"
native_port = 9000
http_port = 8123
secure = false
database = "default"
hackernews_table = "hackernews"
stackoverflow_table = "surveys"
