<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DefaultItemExcludes>$(DefaultItemExcludes);Tests/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="[2.1.89]" />
    <PackageReference Include="Npgsql" Version="[10.0.3]" />
    <Compile Remove="Tests/**/*.cs" />
    <EmbeddedResource Include="sql/migrate.sql" />
  </ItemGroup>
</Project>
