ALTER TABLE quotes MODIFY COLUMN i Array(UInt32);
ALTER TABLE trades MODIFY COLUMN c Array(UInt32);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS ds String DEFAULT '' AFTER s;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS pt UInt64 DEFAULT 0 AFTER ds;
