// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"example.com/playlist-api/ent/item"
	"example.com/playlist-api/ent/playlist"
	"example.com/playlist-api/ent/track"
	"github.com/google/uuid"
)

// Item is the model entity for the Item schema.
type Item struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PlaylistID holds the value of the "playlist_id" field.
	PlaylistID uuid.UUID `json:"playlist_id,omitempty"`
	// TrackID holds the value of the "track_id" field.
	TrackID uuid.UUID `json:"track_id,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ItemQuery when eager-loading is set.
	Edges        ItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ItemEdges holds the relations/edges for other nodes in the graph.
type ItemEdges struct {
	// Playlist holds the value of the playlist edge.
	Playlist *Playlist `json:"playlist,omitempty"`
	// Track holds the value of the track edge.
	Track *Track `json:"track,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlaylistOrErr returns the Playlist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) PlaylistOrErr() (*Playlist, error) {
	if e.Playlist != nil {
		return e.Playlist, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: playlist.Label}
	}
	return nil, &NotLoadedError{edge: "playlist"}
}

// TrackOrErr returns the Track value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) TrackOrErr() (*Track, error) {
	if e.Track != nil {
		return e.Track, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: track.Label}
	}
	return nil, &NotLoadedError{edge: "track"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Item) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case item.FieldPosition:
			values[i] = new(sql.NullInt64)
		case item.FieldID, item.FieldPlaylistID, item.FieldTrackID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Item fields.
func (_m *Item) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case item.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case item.FieldPlaylistID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field playlist_id", values[i])
			} else if value != nil {
				_m.PlaylistID = *value
			}
		case item.FieldTrackID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field track_id", values[i])
			} else if value != nil {
				_m.TrackID = *value
			}
		case item.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Item.
// This includes values selected through modifiers, order, etc.
func (_m *Item) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlaylist queries the "playlist" edge of the Item entity.
func (_m *Item) QueryPlaylist() *PlaylistQuery {
	return NewItemClient(_m.config).QueryPlaylist(_m)
}

// QueryTrack queries the "track" edge of the Item entity.
func (_m *Item) QueryTrack() *TrackQuery {
	return NewItemClient(_m.config).QueryTrack(_m)
}

// Update returns a builder for updating this Item.
// Note that you need to call Item.Unwrap() before calling this method if this Item
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Item) Update() *ItemUpdateOne {
	return NewItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Item entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Item) Unwrap() *Item {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Item is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Item) String() string {
	var builder strings.Builder
	builder.WriteString("Item(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("playlist_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlaylistID))
	builder.WriteString(", ")
	builder.WriteString("track_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrackID))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteByte(')')
	return builder.String()
}

// Items is a parsable slice of Item.
type Items []*Item
