// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"example.com/playlist-api/ent/item"
	"example.com/playlist-api/ent/predicate"
)

// ItemUpdate is the builder for updating Item entities.
type ItemUpdate struct {
	config
	hooks    []Hook
	mutation *ItemMutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (_u *ItemUpdate) Where(ps ...predicate.Item) *ItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPosition sets the "position" field.
func (_u *ItemUpdate) SetPosition(v int) *ItemUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *ItemUpdate) SetNillablePosition(v *int) *ItemUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *ItemUpdate) AddPosition(v int) *ItemUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the ItemMutation object of the builder.
func (_u *ItemUpdate) Mutation() *ItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemUpdate) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := item.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "Item.position": %w`, err)}
		}
	}
	if _u.mutation.PlaylistCleared() && len(_u.mutation.PlaylistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Item.playlist"`)
	}
	if _u.mutation.TrackCleared() && len(_u.mutation.TrackIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Item.track"`)
	}
	return nil
}

func (_u *ItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(item.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(item.FieldPosition, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ItemUpdateOne is the builder for updating a single Item entity.
type ItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemMutation
}

// SetPosition sets the "position" field.
func (_u *ItemUpdateOne) SetPosition(v int) *ItemUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillablePosition(v *int) *ItemUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *ItemUpdateOne) AddPosition(v int) *ItemUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the ItemMutation object of the builder.
func (_u *ItemUpdateOne) Mutation() *ItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (_u *ItemUpdateOne) Where(ps ...predicate.Item) *ItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ItemUpdateOne) Select(field string, fields ...string) *ItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Item entity.
func (_u *ItemUpdateOne) Save(ctx context.Context) (*Item, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemUpdateOne) SaveX(ctx context.Context) *Item {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemUpdateOne) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := item.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "Item.position": %w`, err)}
		}
	}
	if _u.mutation.PlaylistCleared() && len(_u.mutation.PlaylistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Item.playlist"`)
	}
	if _u.mutation.TrackCleared() && len(_u.mutation.TrackIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Item.track"`)
	}
	return nil
}

func (_u *ItemUpdateOne) sqlSave(ctx context.Context) (_node *Item, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Item.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, item.FieldID)
		for _, f := range fields {
			if !item.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != item.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(item.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(item.FieldPosition, field.TypeInt, value)
	}
	_node = &Item{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
