// Code generated by ent, DO NOT EDIT.

package ent

import (
	"example.com/playlist-api/ent/item"
	"example.com/playlist-api/ent/playlist"
	"example.com/playlist-api/ent/schema"
	"example.com/playlist-api/ent/track"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescPosition is the schema descriptor for position field.
	itemDescPosition := itemFields[3].Descriptor()
	// item.PositionValidator is a validator for the "position" field. It is called by the builders before save.
	item.PositionValidator = func() func(int) error {
		validators := itemDescPosition.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(position int) error {
			for _, fn := range fns {
				if err := fn(position); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemDescID is the schema descriptor for id field.
	itemDescID := itemFields[0].Descriptor()
	// item.DefaultID holds the default value on creation for the id field.
	item.DefaultID = itemDescID.Default.(func() uuid.UUID)
	playlistFields := schema.Playlist{}.Fields()
	_ = playlistFields
	// playlistDescName is the schema descriptor for name field.
	playlistDescName := playlistFields[2].Descriptor()
	// playlist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	playlist.NameValidator = func() func(string) error {
		validators := playlistDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// playlistDescRevision is the schema descriptor for revision field.
	playlistDescRevision := playlistFields[3].Descriptor()
	// playlist.DefaultRevision holds the default value on creation for the revision field.
	playlist.DefaultRevision = playlistDescRevision.Default.(int)
	// playlist.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	playlist.RevisionValidator = playlistDescRevision.Validators[0].(func(int) error)
	// playlistDescID is the schema descriptor for id field.
	playlistDescID := playlistFields[0].Descriptor()
	// playlist.DefaultID holds the default value on creation for the id field.
	playlist.DefaultID = playlistDescID.Default.(func() uuid.UUID)
	trackFields := schema.Track{}.Fields()
	_ = trackFields
	// trackDescTitle is the schema descriptor for title field.
	trackDescTitle := trackFields[1].Descriptor()
	// track.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	track.TitleValidator = func() func(string) error {
		validators := trackDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// trackDescArtist is the schema descriptor for artist field.
	trackDescArtist := trackFields[2].Descriptor()
	// track.ArtistValidator is a validator for the "artist" field. It is called by the builders before save.
	track.ArtistValidator = func() func(string) error {
		validators := trackDescArtist.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(artist string) error {
			for _, fn := range fns {
				if err := fn(artist); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// trackDescDurationSeconds is the schema descriptor for duration_seconds field.
	trackDescDurationSeconds := trackFields[3].Descriptor()
	// track.DurationSecondsValidator is a validator for the "duration_seconds" field. It is called by the builders before save.
	track.DurationSecondsValidator = func() func(int) error {
		validators := trackDescDurationSeconds.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(duration_seconds int) error {
			for _, fn := range fns {
				if err := fn(duration_seconds); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
