// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"example.com/playlist-api/ent/item"
	"example.com/playlist-api/ent/predicate"
	"example.com/playlist-api/ent/track"
	"github.com/google/uuid"
)

// TrackUpdate is the builder for updating Track entities.
type TrackUpdate struct {
	config
	hooks    []Hook
	mutation *TrackMutation
}

// Where appends a list predicates to the TrackUpdate builder.
func (_u *TrackUpdate) Where(ps ...predicate.Track) *TrackUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TrackUpdate) SetTitle(v string) *TrackUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TrackUpdate) SetNillableTitle(v *string) *TrackUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetArtist sets the "artist" field.
func (_u *TrackUpdate) SetArtist(v string) *TrackUpdate {
	_u.mutation.SetArtist(v)
	return _u
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_u *TrackUpdate) SetNillableArtist(v *string) *TrackUpdate {
	if v != nil {
		_u.SetArtist(*v)
	}
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *TrackUpdate) SetDurationSeconds(v int) *TrackUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *TrackUpdate) SetNillableDurationSeconds(v *int) *TrackUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *TrackUpdate) AddDurationSeconds(v int) *TrackUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_u *TrackUpdate) AddItemIDs(ids ...uuid.UUID) *TrackUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the Item entity.
func (_u *TrackUpdate) AddItems(v ...*Item) *TrackUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the TrackMutation object of the builder.
func (_u *TrackUpdate) Mutation() *TrackMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the Item entity.
func (_u *TrackUpdate) ClearItems() *TrackUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (_u *TrackUpdate) RemoveItemIDs(ids ...uuid.UUID) *TrackUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to Item entities.
func (_u *TrackUpdate) RemoveItems(v ...*Item) *TrackUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrackUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrackUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrackUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrackUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrackUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := track.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Track.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Artist(); ok {
		if err := track.ArtistValidator(v); err != nil {
			return &ValidationError{Name: "artist", err: fmt.Errorf(`ent: validator failed for field "Track.artist": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationSeconds(); ok {
		if err := track.DurationSecondsValidator(v); err != nil {
			return &ValidationError{Name: "duration_seconds", err: fmt.Errorf(`ent: validator failed for field "Track.duration_seconds": %w`, err)}
		}
	}
	return nil
}

func (_u *TrackUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(track.Table, track.Columns, sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(track.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Artist(); ok {
		_spec.SetField(track.FieldArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(track.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(track.FieldDurationSeconds, field.TypeInt, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   track.ItemsTable,
			Columns: []string{track.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   track.ItemsTable,
			Columns: []string{track.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   track.ItemsTable,
			Columns: []string{track.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{track.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrackUpdateOne is the builder for updating a single Track entity.
type TrackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrackMutation
}

// SetTitle sets the "title" field.
func (_u *TrackUpdateOne) SetTitle(v string) *TrackUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TrackUpdateOne) SetNillableTitle(v *string) *TrackUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetArtist sets the "artist" field.
func (_u *TrackUpdateOne) SetArtist(v string) *TrackUpdateOne {
	_u.mutation.SetArtist(v)
	return _u
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_u *TrackUpdateOne) SetNillableArtist(v *string) *TrackUpdateOne {
	if v != nil {
		_u.SetArtist(*v)
	}
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *TrackUpdateOne) SetDurationSeconds(v int) *TrackUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *TrackUpdateOne) SetNillableDurationSeconds(v *int) *TrackUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *TrackUpdateOne) AddDurationSeconds(v int) *TrackUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_u *TrackUpdateOne) AddItemIDs(ids ...uuid.UUID) *TrackUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the Item entity.
func (_u *TrackUpdateOne) AddItems(v ...*Item) *TrackUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the TrackMutation object of the builder.
func (_u *TrackUpdateOne) Mutation() *TrackMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the Item entity.
func (_u *TrackUpdateOne) ClearItems() *TrackUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (_u *TrackUpdateOne) RemoveItemIDs(ids ...uuid.UUID) *TrackUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to Item entities.
func (_u *TrackUpdateOne) RemoveItems(v ...*Item) *TrackUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the TrackUpdate builder.
func (_u *TrackUpdateOne) Where(ps ...predicate.Track) *TrackUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrackUpdateOne) Select(field string, fields ...string) *TrackUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Track entity.
func (_u *TrackUpdateOne) Save(ctx context.Context) (*Track, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrackUpdateOne) SaveX(ctx context.Context) *Track {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrackUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrackUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrackUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := track.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Track.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Artist(); ok {
		if err := track.ArtistValidator(v); err != nil {
			return &ValidationError{Name: "artist", err: fmt.Errorf(`ent: validator failed for field "Track.artist": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationSeconds(); ok {
		if err := track.DurationSecondsValidator(v); err != nil {
			return &ValidationError{Name: "duration_seconds", err: fmt.Errorf(`ent: validator failed for field "Track.duration_seconds": %w`, err)}
		}
	}
	return nil
}

func (_u *TrackUpdateOne) sqlSave(ctx context.Context) (_node *Track, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(track.Table, track.Columns, sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Track.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, track.FieldID)
		for _, f := range fields {
			if !track.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != track.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(track.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Artist(); ok {
		_spec.SetField(track.FieldArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(track.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(track.FieldDurationSeconds, field.TypeInt, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   track.ItemsTable,
			Columns: []string{track.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   track.ItemsTable,
			Columns: []string{track.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   track.ItemsTable,
			Columns: []string{track.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Track{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{track.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
