\set ON_ERROR_STOP on
\getenv migrator_password USAGE_MIGRATOR_PASSWORD
\getenv app_password USAGE_APP_PASSWORD
\getenv cdc_password USAGE_CDC_PASSWORD
BEGIN;
CREATE ROLE usage_owner NOLOGIN;
CREATE ROLE usage_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'migrator_password';
CREATE ROLE usage_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'app_password';
CREATE ROLE usage_cdc LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE REPLICATION PASSWORD :'cdc_password';
GRANT usage_owner TO usage_migrator;
GRANT usage_owner TO CURRENT_USER;
CREATE SCHEMA usage AUTHORIZATION usage_owner;
REVOKE ALL ON SCHEMA usage FROM PUBLIC;
GRANT USAGE ON SCHEMA usage TO usage_app, usage_cdc;
ALTER ROLE usage_app SET statement_timeout = '20s';
COMMIT;
